### ISSUE TITLE
Download Excel Template address columns

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#101]
This is not done address related fields are still visible.

**Comment by manasghosh81** [comment]
@mayank2k2 : As per discussion with Sumit, the address fields will be there, we cannot remove that. We have set blanks within the dropdowns so that no other value other than blanks can be entered. Please talk to Sumit and close this.

**Comment by manasghosh81** [comment]
As discussed in our defect Triage meeting we have checked this ,we can not hide these field as we need to remove certain code for validation that we have written earlier  and we need to check all the validation again

**Comment by mayank2k2** [comment]
I am not agree can you show me what code you need to modify, we don't need these columns

**Comment by manasghosh81** [comment]
@mayank2k2 : I have sent you the email (16th Feb) where we communicated the details about address field input regarding bulk upload. At this point in time, I cannot take the risk of any modification to bulk upload process. We have tested by removing the address fields from the excel and the program is not throwing error as these are the rightmost fields. But beware that even if address fields are removed, if user types in anything on these columns that will be treated as address as program still considers column L to Q as address fields. 

Moreover, if this change is made the export program has to be changed in order to make the exported excel in sync as well.

The code is in ValidateUploadFile and ProcessUploadFile in UI Helper folder.

Thanks & regards
Subha

**Comment by mayank2k2** [comment]
Thanks subha !
i discuss this with manas and sumit as well, so we will be hiding these columns (L-Q) from template, so that end user will not confuse. also please update instruction accordingly.

![image](https://cloud.githubusercontent.com/assets/16239450/13491285/abdd97dc-e157-11e5-94c9-181728f3287e.png)

after hiding this should be similar to this
![image](https://cloud.githubusercontent.com/assets/16239450/13491321/d073fdd4-e157-11e5-9274-11833b058ad3.png)

**Comment by mayank2k2** [comment]
assigned to manas for his update

**Comment by madhumitadey** [comment]
On downloading a bulk upload template, we could still see address fields in the Student and Teacher tab. They should be hidden as per the discussion. Please see and correct.

![image](https://cloud.githubusercontent.com/assets/16831474/13519000/496da900-e1f9-11e5-84a5-a27da80f5ba8.png)

**Comment by mayank2k2** [comment]
As discussed with Manas & Subha, we are hiding columns (L-Q) from template with removing headers text and make background color white.

same changes for export and error file as well,
Hiding the list sheet
Remove the address related information from instruction.

low: it will be great if  hide the username from blank template while downloading but should be visible if we exporting data.

**Comment by mayank2k2** [comment]
Hi Manas, ad discussed yesterday.
i see  list sheet is not hidden
[Upload_User_Template_V1.0.xlsx](https://github.com/OUPMATH/OxfordMath_UAT/files/164973/Upload_User_Template_V1.0.xlsx)

also columns (L-Q) in error file are not hidden/minimize the width
[Upload_User_Template_V1.0_-_Copy_Error.xlsx](https://github.com/OUPMATH/OxfordMath_UAT/files/164974/Upload_User_Template_V1.0_-_Copy_Error.xlsx)

**Comment by manasghosh81** [comment]
Please recheck this.Now we have remove the address validation from code as well as excel.

**Comment by mayank2k2** [comment]
now looks fine
