### ISSUE TITLE
Performance report page from teacher login

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#108]
Step 1  Open the OUP my maths url in a browser
Step 2  Provide the Teacher  login credential and click on login.
Step 3  Click on reports link
Step 4  Click the Student performance from the reports
Step 5  Fill the details and click on search
Step 6  Click on the view icon under action

Except for 'print', nothing else is clickable. The topic tiles should show question-wise breakup of marks.
Note: Similar issue exists in student login also.
![image](https://cloud.githubusercontent.com/assets/16831643/13450782/0232329a-e05f-11e5-9398-e4ce8b603b5d.png)

The print format of individual student reports also looks clumsy:
![image](https://cloud.githubusercontent.com/assets/16831643/13450861/bb23d5a6-e05f-11e5-954d-4f3aae4bfd39.png)

On clicking back button of the browser or close button of the page, it is going back to 'Reports' page. It should instead move back to the previous search page containing student details.

**Comment by manasghosh81** [comment]
@kirti-sharma : This is Subha.
1) As per the current functionality nothing else should be clickable. We are discussing with Soma and Sumit to have a functionality to add click to tiles to show the Q1 and Q2 score in a popup. So that is an enhancement and if possible, will be taken care separately.
2) This is a browser functionality and that the browser always opens PDF in a different tab. and back button of the browser will behave as per the browser, the application does not have any control on it. 
3) Since an open source PDf converter is used to convert the screen content into PDF, the look and feel cannot be improved any further. However we have actually printed it on a piece of paper and it does not look that clumsy, it is looking perfect with proper margin - please check that. 
- Appreciate if you can check it and close this defect.

**Comment by manasghosh81** [comment]
This is fixed and available in UAT now

**Comment by kirti-sharma** [comment]
Fixed.
