### ISSUE TITLE
Performance report page from teacher login 2

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#119]
Login with teacher credentials and go to student performance page. Click on one student performance.
Present functionality: Chapter number missing on report page.
![image](https://cloud.githubusercontent.com/assets/16831643/13600001/2a8e4872-e54c-11e5-8f7c-25aeffba0d8b.png)

Required functionality: As per FSD, chapter number should appear before chapter name. Please refer the screeshot.

![image](https://cloud.githubusercontent.com/assets/16831643/13519345/df04c3d8-e1fc-11e5-99df-ff4b8c766e77.png)

**Comment by manasghosh81** [comment]
@kirti-sharma : Hi, Can you discuss this with Soma once? We had a meeting between, Soma, Sumit and myself, regarding chapter numbers and it was decided in that meeting that chapter numbers will come in the resources page, but may not come in the reports. That is the main reason why chapter number was separated out from chapter name. Moreover, this diagram from the FSD represents "Chapter 01" as the name of the chapter, since we didn't have the actual chapter names during that time.

@somabanerjee : Can you please confirm this?

Regards
Subha

**Comment by somabanerjee** [comment]
Hi Subha: We had agreed to put in chapter numbers and names together. There was some discussion regarding how this is to be implemented at the back-end between you and Sumit, which I do not recall.

**Comment by manasghosh81** [comment]
@somabanerjee - Please tell us where to put chapter code? Do you want to put those in Student dashboard tiles, Teacher chapterwise performance reports and everywhere where there is chapter name displayed?

**Comment by somabanerjee** [comment]
@manasghosh81 Put the chapter number before the chapter name, as it appears in the resources.

**Comment by kirti-sharma** [comment]
Fixed.
