### ISSUE TITLE
Re-Activate User Issue

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#54]
Search any user using OUP Admin, de-activate it, user successfully deactivated,

Now reactivate it again getting error on reactivating also class and section not displaying, see attached the screen shot,  

Note:- This was working earlier. 
![re-activate user issue](https://cloud.githubusercontent.com/assets/16239450/12939753/17101816-cfe9-11e5-9679-03750eda7f62.JPG)

**Comment by manasghosh81** [comment]
HI Mayank - Can you please check this? I think the error was because, there is an active student with the same roll number in same class and section - which means the school has reused the roll number to enroll a new student. This check is also applied in bulk upload process where you cannot upload 2 students with same class, section and roll number.

**Comment by mayank2k2** [comment]
NO this is not fixed if i search user with roll number 1002, 3 user populated with different i roll number, first name , last name. I de-activated last user it sucessfully deactivated but when i re-activated , it is throwing validation error. see attached.
![re-activate user issue 54](https://cloud.githubusercontent.com/assets/16239450/13134572/fa7f7944-d62d-11e5-94f1-1c0edc114b0c.JPG)

**Comment by mayank2k2** [comment]
Also if you see highlighted row the class and section not displaying after deactivate.

**Comment by manasghosh81** [comment]
We are not able to reproduce this issue.This might be a data issue.We will check this with fresh set of data try to reproduce this issue

**Comment by mayank2k2** [comment]
working fine

**Comment by mayank2k2** [comment]
As shown deactivating user is removing class/section value from screen.

**Comment by manasghosh81** [comment]
It is working find in UAT.

![image](https://cloud.githubusercontent.com/assets/12447431/13470240/4a377916-e0d1-11e5-93c3-a88c0703d1cb.png)

**Comment by mayank2k2** [comment]
i have shown this refresh behavior to you you need to hit search, see this

![image](https://cloud.githubusercontent.com/assets/16239450/13485184/0c002f1c-e12b-11e5-8df0-fcce390d5a51.png)

**Comment by manasghosh81** [comment]
**@mayank2k2 :** This is appearing because user is also de-activated from **usersectionmappings** table.We have to this as we have search criteria with class and section also.Once user is deactivated it also deactivated from mappings table also,so that it should not appear in search result.

Once the user is deactivated,it has no class-section physically but directly associated to school at that point of time

**Comment by mayank2k2** [comment]
so what is this, i don't understand i have shown you yesterday

![image](https://cloud.githubusercontent.com/assets/16239450/13485501/714b3c6a-e12e-11e5-83c3-5df50d20235b.png)

**Comment by manasghosh81** [comment]
@mayank2k2 : This is because, the table is not getting refreshed once a user is deleted or reactivated, we are looking into it.

Regards
Subha

**Comment by manasghosh81** [comment]
@mayank2k2 :If user is deactivated,then  both class and section column will be displayed as "N.A".Once it is reactivated again,the class and section will appear again

**Comment by mayank2k2** [comment]
working fine
